Kuz 24 implement scroll api
kuzzleio/sdk-php pull request #25
Opened 2016-11-02 16:41 UTC by stafyniaksacha

* Migrate `advancedSearch` method to `search`
* Implement scroll api 
* Update samples in `examples/document.php`

fixes #24 & #22

2016-11-07 17:58 UTC, benoitvidis approved these changes

2016-11-08 09:20 UTC, dbengsch approved these changes

2016-11-08 10:53 UTC, scottinet requested changes

2016-11-08 10:53 UTC, scottinet commented on src/DataCollection.php
> +        while ($searchResult) {
I'm not confortable with this solution: if there are tens of thousands documents (or millions of them), you'll saturate the memory with no mean for the client to know what's going on.

I would either return a paginated result, like `search` does, or put a hard limit on the maximum number of documents that can be fetched that way, with an explicit message advising the use of `search` when the number of documents is too high.

2016-11-18 12:56 UTC, scottinet approved these changes

2016-11-18 12:56 UTC, merged