Adapt to request model and controller refactor
kuzzleio/sdk-php pull request #38
Opened 2016-12-14 13:40 UTC by dbengsch

fix #34 and #35

2016-12-15 15:03 UTC, benoitvidis approved these changes

2016-12-15 15:07 UTC, scottinet approved these changes

2016-12-15 15:08 UTC, scottinet requested changes
Don't mind this comment.

2016-12-15 15:10 UTC, scottinet approved these changes

2016-12-16 10:19 UTC, stafyniaksacha requested changes
Missing changes in: https://github.com/kuzzleio/sdk-php/blob/master/src/config/routes.json

2016-12-16 10:41 UTC, dbengsch commented
@stafyniaksacha I'm pretty sure I changed it

2016-12-16 10:43 UTC, stafyniaksacha approved these changes

2016-12-16 10:44 UTC, merged