Factory method refactor
kuzzleio/sdk-php pull request #42
Opened 2016-12-19 17:09 UTC by xbill82

Fixes #40 and introduces a lot of wonderful breaking changes :heart:

2016-12-20 08:33 UTC, scottinet requested changes

2016-12-20 08:33 UTC, scottinet commented on src/DataMapping.php
> +    public function __construct(Collection $kuzzleDataCollection, array $mapping = [])
`kuzzleDataCollection` => `collection`

2016-12-20 08:33 UTC, scottinet commented on src/Collection.php
>       * Creates a new KuzzleDataMapping object, using its constructor.
Comment needs update

2016-12-20 08:33 UTC, scottinet commented on src/Collection.php
> +    public function collectionMapping(array $mapping = [])
Why `collectionMapping` and not `mapping`?

2016-12-20 08:33 UTC, scottinet commented on src/DataMapping.php
>  class DataMapping
Hasn't this file been replaced by `Mapping.php`?

2016-12-20 08:33 UTC, scottinet commented on src/Mapping.php
> +    public function __construct(Collection $kuzzleDataCollection, array $mapping = [])
`$kuzzleDataCollection` should be renamed

2016-12-20 08:33 UTC, scottinet commented on src/Mapping.php
> +     * Instantiates a new KuzzleDataMapping object with an up-to-date content.
`KuzzleDataMapping` has been renamed

2016-12-20 08:33 UTC, scottinet commented on src/Util/SearchResult.php
> +    public function __construct(Collection $dataCollection, $total, array $documents, array $aggregations = [], array $searchArgs = [], SearchResult $previous = null)
`$dataCollection` should also be renamed

2016-12-20 08:36 UTC, scottinet commented on src/Collection.php
> +    public function collectionMapping(array $mapping = [])
Edit: if there is consensus over `collectionMapping` then I would rename all uses of the `Mapping` name (files, classes name, etc) into `CollectionMapping`, for the sake of consistency.

2016-12-21 16:59 UTC, xbill82 commented
@scottinet @ballinette same thing as per kuzzleio/sdk-javascript#159

2017-01-02 14:52 UTC, xbill82 commented on src/DataMapping.php
>  class DataMapping
This file should have been deleted (since yes, the new version is called `Mapping.php`)

2017-01-02 14:53 UTC, xbill82 commented on src/DataMapping.php
> +    public function __construct(Collection $kuzzleDataCollection, array $mapping = [])
Just deleted this file.

2017-01-03 10:08 UTC, scottinet approved these changes

2017-01-04 17:16 UTC, dbengsch approved these changes

2017-01-04 17:16 UTC, merged