Collection.createDocument: rename the updateIfExist option
kuzzleio/sdk-php pull request #55
Opened 2017-02-15 10:01 UTC by scottinet

# Description

The `Collection.createDocument` method accepts a `updateIfExist` option.
Since this option really replaces the document if it already exists, it is dangerously confusing.

This PR change this option name to `ifExist` and its accepted value to one of these 2 values: `error` (default) or `replace`
If an invalid value is provided, the method throws an `InvalidArgumentException` exception.

# Solved issue

#54

2017-02-15 10:05 UTC, xbill82 approved these changes

2017-02-17 14:35 UTC, dbengsch approved these changes

2017-02-21 10:01 UTC, stafyniaksacha requested changes

2017-02-21 10:01 UTC, stafyniaksacha commented on composer.json
> +  "version": "2.3.0",
Bad bump

2017-02-21 10:10 UTC, scottinet commented on composer.json
> +  "version": "2.3.0",
Fixed.

2017-03-03 14:00 UTC, stafyniaksacha approved these changes

2017-03-03 14:00 UTC, merged