Standardize memory storage
kuzzleio/sdk-php pull request #59
Opened 2017-03-14 12:44 UTC by scottinet

# Description

Make the `MemoryStorage` object on par with the newly refactored corresponding controller and with the new SDK reference.

2017-03-14 13:22 UTC, dbengsch requested changes
Nice work !

2017-03-14 13:22 UTC, dbengsch commented on src/MemoryStorage.php
> +        if ($argsLeft == 1) {
`===` instead of `==`

2017-03-14 15:36 UTC, scottinet commented on src/MemoryStorage.php
> +        if ($argsLeft == 1) {
fixed

2017-03-20 16:03 UTC, dbengsch approved these changes

2017-03-22 11:54 UTC, stafyniaksacha requested changes

2017-03-22 11:54 UTC, stafyniaksacha commented on src/MemoryStorage.php
> +        if (!isset($this->COMMANDS[$command])) {
usage of `array_key_exists` is required, `isset` will throw an error if there are no `$command` key into `$this->COMMANDS` array

2017-03-22 12:12 UTC, scottinet commented on src/MemoryStorage.php
> +        if (!isset($this->COMMANDS[$command])) {
That does not seem to be the case according to [PHP documentation](http://php.net/manual/en/function.isset.php), where it is stated that the only difference between these two methods, is that `isset` returns FALSE if an element is set but equals to NULL, where in that specific case, `array_key_exists` will return TRUE.

Other than that, using `isset` on an unexisting element of an array should simply return FALSE.

2017-03-22 12:56 UTC, stafyniaksacha approved these changes

2017-03-23 10:58 UTC, merged