Allow paginated search using ES's search_after in SearchResult:fetchNext
kuzzleio/sdk-php pull request #78
Opened 2017-06-16 15:01 UTC by samniisan

## Introduces
- Way to use ES's search_after if conditions are met when calling SearchResult:fetchNext (better than using scrolls, bypasses the default search limit count)
- New unit tests to cover SearchResult functionalities

## Boyscoot
- Updates README.md (typos / various)
- PHPDoc fixes, invalid variable names, code cleanup

2017-06-19 10:39 UTC, stafyniaksacha commented on README.md
> +## Basic usage
:+1:

2017-06-19 10:42 UTC, stafyniaksacha approved these changes

2017-06-19 13:56 UTC, scottinet commented
I've raised a question on the Javascript SDK implementation of this feature: https://github.com/kuzzleio/sdk-javascript/pull/233#pullrequestreview-44849333

It may be a good idea to take a look at it before merging this PR, to check if this is worth considering or not.

2017-06-19 14:29 UTC, benoitvidis requested changes

2017-06-19 14:29 UTC, benoitvidis commented on src/Util/SearchResult.php
> +        } else if (array_key_exists('scrollId', $this->options)) {
if a scroll was explicitly requested, it should not be bypassed.

2017-06-19 14:29 UTC, benoitvidis commented on src/Util/SearchResult.php
> +            && !array_key_exists('from', $this->options)) {
Why not use search after if `from` is set? Removing it from the search after request should still be consistent.

2017-06-20 11:40 UTC, samniisan commented
PR updated, scroll is now prioritized as long as the user specifies a scroll param.

2017-06-20 13:28 UTC, dbengsch approved these changes

2017-06-21 09:37 UTC, ballinette approved these changes

2017-07-17 14:34 UTC, merged