[KZL-375] Server controller
kuzzleio/sdk-php pull request #97
Opened 2018-08-07 18:06 UTC by alexandrebouthinon

## What does this PR do ?
Add refactored Server Controller with with his unit tests

### How should this be manually tested?
Run:
```bash
$ php ./vendor/bin/phpunit
$ php ./vendor/bin/phpcs -p -n --standard=PSR2 src
```

2018-08-09 12:56 UTC, Njuelle approved these changes

2018-08-13 09:30 UTC, benoitvidis requested changes

2018-08-13 09:30 UTC, benoitvidis commented on src/Server.php
> +    public function getInfo(array $options = [])
Why not `info`  like in the api and in go?

2018-08-13 15:11 UTC, xbill82 approved these changes

2018-08-13 15:49 UTC, benoitvidis approved these changes

2018-08-13 20:47 UTC, merged